insert into books (id, title, publishDate, author, page, coverImage) values (1,'The Road Less Traveled','1989-10-07', 'Ernestina Kozey', 42,'http://lorempixel.com/35/50/nature/');
insert into books (id, title, publishDate, author, page, coverImage) values (2,'Vile Bodies','1989-04-12', 'Miss Geo Nienow', 10,'http://lorempixel.com/35/50/cats/');
insert into books (id, title, publishDate, author, page, coverImage) values (3,'Time To Murder And Create','1980-02-18', 'Marcos Cronin', 34,'http://lorempixel.com/35/50/business/');
insert into books (id, title, publishDate, author, page, coverImage) values (4,'Cover Her Face','1966-06-29', 'Susana Crist', 02,'http://lorempixel.com/35/50/transport/');
insert into books (id, title, publishDate, author, page, coverImage) values (5,'The Stars Tennis Balls','1966-12-21', 'Shanna Reichel DDS', 15,'http://lorempixel.com/35/50/cats/');
insert into books (id, title, publishDate, author, page, coverImage) values (6,'Stranger in a Strange Land','1989-06-06', 'Nichole Mann V', 62,'http://lorempixel.com/35/50/animals/');
insert into books (id, title, publishDate, author, page, coverImage) values (7,'Its a Battlefield','1964-02-24', 'Dr. Brendan Huels', 87,'http://lorempixel.com/35/50/fashion/');
insert into books (id, title, publishDate, author, page, coverImage) values (8,'The Parliament of Man','1965-04-28', 'Marcos Kutch', 57,'http://lorempixel.com/35/50/business/');
insert into books (id, title, publishDate, author, page, coverImage) values (9,'Those Barren Leaves, Thrones, Dominations','1989-09-02', 'Corene Koepp', 20,'http://lorempixel.com/35/50/cats/');
insert into books (id, title, publishDate, author, page, coverImage) values (10,'Tiger! Tiger!','1956-01-03', 'Lacey Hessel', 75,'http://lorempixel.com/35/50/business/');
insert into books (id, title, publishDate, author, page, coverImage) values (11,'Butter In a Lordly Dish','1956-02-25', 'Dr. Aliyah Lindgren', 05,'http://lorempixel.com/35/50/food/');
insert into books (id, title, publishDate, author, page, coverImage) values (12,'Rosemary Sutcliff','1952-06-06', 'Aurore Wilderman', 24,'http://lorempixel.com/35/50/sports/');
insert into books (id, title, publishDate, author, page, coverImage) values (13,'A Scanner Darkly','1963-08-09', 'Dr. Garrison Gorczany', 85,'http://lorempixel.com/35/50/nightlife/');
insert into books (id, title, publishDate, author, page, coverImage) values (14,'Stranger in a Strange Land','1986-09-04', 'Jakayla Quitzon', 26,'http://lorempixel.com/35/50/cats/');
insert into books (id, title, publishDate, author, page, coverImage) values (15,'Dance Dance Dance','1984-10-11', 'Marisa Dietrich', 12,'http://lorempixel.com/35/50/transport/');
insert into books (id, title, publishDate, author, page, coverImage) values (16,'After Many a Summer Dies the Swan','1957-12-18', 'Claudia Bode Jr.', 91,'http://lorempixel.com/35/50/city/');
insert into books (id, title, publishDate, author, page, coverImage) values (17,'To a God Unknown','1977-01-22', 'Casimer Rolfson', 86,'http://lorempixel.com/35/50/cats/');
insert into books (id, title, publishDate, author, page, coverImage) values (18,'A Time to Kill','1959-11-10', 'Serena Daugherty', 29,'http://lorempixel.com/35/50/people/');
insert into books (id, title, publishDate, author, page, coverImage) values (19,'Noli Me Tangere','1997-02-17', 'Jules Schuppe', 57,'http://lorempixel.com/35/50/food/');
insert into books (id, title, publishDate, author, page, coverImage) values (20,'Noli Me Tangere','1959-04-11', 'Mrs. Noelia Moen', 65,'http://lorempixel.com/35/50/transport/');
insert into books (id, title, publishDate, author, page, coverImage) values (21,'Dance Dance Dance','1965-11-12', 'Gaston Streich', 26,'http://lorempixel.com/35/50/food/');
insert into books (id, title, publishDate, author, page, coverImage) values (22,'O Jerusalem!','1952-06-14', 'Kiel Becker', 60,'http://lorempixel.com/35/50/nightlife/');
insert into books (id, title, publishDate, author, page, coverImage) values (23,'A Passage to India','1956-06-03', 'Miss Jacey Klocko', 24,'http://lorempixel.com/35/50/transport/');
insert into books (id, title, publishDate, author, page, coverImage) values (24,'The Mirror Crackd from Side to Side','1974-09-30', 'Aiyana Terry', 69,'http://lorempixel.com/35/50/cats/');
insert into books (id, title, publishDate, author, page, coverImage) values (25,'The Sun Also Rises','1998-08-28', 'Brenna Maggio', 35,'http://lorempixel.com/35/50/technics/');
insert into books (id, title, publishDate, author, page, coverImage) values (26,'Time of our Darkness','1969-01-05', 'Destiney Morar', 28,'http://lorempixel.com/35/50/city/');
insert into books (id, title, publishDate, author, page, coverImage) values (27,'Surprised by Joy','1999-06-20', 'Johnpaul Corkery IV', 33,'http://lorempixel.com/35/50/fashion/');
insert into books (id, title, publishDate, author, page, coverImage) values (28,'The Last Enemy','1961-05-10', 'Boris Hahn IV', 43,'http://lorempixel.com/35/50/nature/');
insert into books (id, title, publishDate, author, page, coverImage) values (29,'A Time of Gifts','1992-10-16', 'Genevieve OConner', 17,'http://lorempixel.com/35/50/cats/');
insert into books (id, title, publishDate, author, page, coverImage) values (30,'If I Forget Thee Jerusalem','1993-10-14', 'Lenny Bauch', 11,'http://lorempixel.com/35/50/people/');